version: "3"

services:
    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
    bff:
        build: ./packages/bff
        environment:
            - REDIS_HOST=redis
        ports:
            - "8000:8000"
        depends_on:
            - redis
        volumes:
            - ./packages/bff/:/usr/app
            - /urs/app/node_modules
    client:
        build: ./packages/client
        ports:
            - "3000:3000"
        depends_on:
            - bff
volumes:
    cache:
