version: "3"

services:
    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
    bff:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - redis
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
volumes:
    cache:
